site_name: Nexiant Voice
site_url: https://nexiant.ai
site_author: Nexiant
site_description: Voice typing for the Linux desktop
repo_url: https://nexiant.ai
theme:
  name: material
  logo: assets/logo-square-512.png
  favicon: assets/apple-touch-icon.png
  features:
    - navigation.footer
  palette:
    # See: https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#automatic-light-dark-mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: brown
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: brown
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
exclude_docs: |
  !.well-known/
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - attr_list
  - admonition
nav:
  - Home: index.md
  - Getting Started:
    - getting-started.md
    - Set Up a Keyboard Shortcut: keyboard-shortcut.md
  - User Guide: user-guide.md
  - Troubleshooting: troubleshooting.md
  - FAQ: faq.md
  - Support: support.md
copyright: Copyright &copy; 2026 Nexiant
extra:
  social:
    - icon: fontawesome/solid/globe
      link: https://nexiant.ai
